export const handleError = (err) => {
  console.error(err.message)
  process.exit(1)
}
